#pragma once

/// BCDL — BPU Computational Deep Learning. Umbrella header.
#include "bcdl/backend/engine.h"
#include "bcdl/core/mem_pool.h"
#include "bcdl/core/status.h"
#include "bcdl/core/sys_mem.h"
#include "bcdl/core/task.h"
#include "bcdl/media/jpeg_codec.h"
#include "bcdl/media/video_codec.h"
#include "bcdl/pipeline/async_detection_pipeline.h"
#include "bcdl/pipeline/detection_pipeline.h"
#include "bcdl/pipeline/stereo_pipeline.h"
#include "bcdl/preproc/geometry.h"
#include "bcdl/preproc/letterbox.h"
#include "bcdl/preproc/letterbox_cpu.h"
#include "bcdl/preproc/vp_image.h"
#include "bcdl/tasks/classification.h"
#include "bcdl/tasks/depth.h"
#include "bcdl/tasks/detection.h"
#include "bcdl/tasks/instance_seg.h"
#include "bcdl/tasks/obb.h"
#include "bcdl/tasks/ocr.h"
#include "bcdl/tasks/pose.h"
#include "bcdl/tasks/segmentation.h"
#include "bcdl/tracks/byte_tracker.h"
